# This is a basic workflow to help you get started with Actions

name: Check for Contributor License Agreement signature

# Controls when the workflow will run
on:
  pull_request:
    types:
      - opened
#    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch: 

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # How do I get the GitHub login?
      - name: Debugging
        run: |
          echo "Pull request created by ${{ github.event.pull_request.user.login }}"
      # Checks if the author has signed the feenk CLA
      - name: Make HTTP request
        run: |
          curl curl -s -o /dev/null --write-out "%{http_code}\n" "https://contributor-license-agreement-database.gadget.app/signatureExistsFor?gitHubUsername=${{ github.event.pull_request.user.login }}" | grep --quiet 200
#      - name: Check JSON response
#        run: |
#          echo "${{ steps.http.outputs }}" # output the JSON response
#          echo "${{ steps.http.outputs.data }}" # output the JSON response
#          # you can now use a JSON parsing tool to extract the desired data from the response
