name: Check for Contributor License Agreement signature

# Controls when the workflow will run
on:
  pull_request:
    types:
      - opened
#     branches: [ "main" ]

  # Allow this workflow to be manually executed from the Actions tab
#   workflow_dispatch: 

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  # This is the job name:
  check-contributor-license-agreement:
    permissions:
      issues: write
      pull-requests: write
  
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
#     outputs:
#       output1: ${{ steps.request-cla-status-for-github-login.outputs.test }}
#       output2: ${{ steps.step2.outputs.test }}

# We can also save scripts in .github/scripts/whatever.rb

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - id: request-cla-status-for-github-login
        name: Make HTTP request to check if the pull request author has signed the feenk CLA
        run: |
          curl -s -o /dev/null --write-out "%{http_code}\n" "https://contributor-license-agreement-database.gadget.app/signatureExistsFor?gitHubUsername=${{ github.event.pull_request.user.login }} | grep --quiet 200 "
#          curl -s -o /dev/null --write-out "signature-exists-response=%{http_code}\n" "https://contributor-license-agreement-database.gadget.app/signatureExistsFor?gitHubUsername=${{ github.event.pull_request.user.login }}" >> "$GITHUB_OUTPUT"
        
#       - id: check-request-status
#         run: |
#           ruby -e "exit 1 if Integer(${{ steps.request-cla-status-for-github-login.outputs.test }}) == 404"
      - id: add-comment-to-pull-request
#         if: ${{ failure() && steps.check-request-status.conclusion == 'failure' }}
        if: ${{ failure() }}
        run: |
          echo "Please sign the CLA" 
          echo "Sending a request to ${{ github.event.pull_request.comments_url }}" &&
          curl --no-progress-meter 
            -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}"\
            -H "X-GitHub-Api-Version: 2022-11-28" \
            ${{ github.event.pull_request.comments_url }} \
            -d '{"body":"Hello and thanks for contributing! To accept your help and merge your pull request, please take a look at and sign our Contributor License Agreement by visiting https://gtoolkit.com/contributor-license-agreement/"}'
