name: Check for Contributor License Agreement signature

# Controls when the workflow will run
on:
  pull_request:
    types:
      - opened
#     branches: [ "main" ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  # This is the job name:
  check-contributor-license-agreement:
    permissions:
      issues: write
      pull-requests: write
  
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Scripts saved in .github/scripts/whatever.rb are available to the runner

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - id: request-cla-status-for-github-login
        name: Make HTTP request to check if the pull request author has signed the feenk CLA
        run: |
          curl -s -o /dev/null --write-out "%{http_code}\n" "https://contributor-license-agreement-database.g
      - id: add-comment-to-pull-request
        if: ${{ failure() }}
        run: |
          echo "Please sign the CLA" &&
          echo "Sending a request to ${{ github.event.pull_request.comments_url }}" &&
          curl --location \
            --request POST \
            --header "Accept: application/vnd.github+json" \
            --header "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}"\
            --header "X-GitHub-Api-Version: 2022-11-28" \
            --data '{"body":"Hello ${{ github.event.pull_request.sender.login }} and thanks for contributing! To accept your help and merge your pull request, please take a look at and sign our Contributor License Agreement by visiting https://gtoolkit.com/contributor-license-agreement/"}' \
            ${{ github.event.pull_request.comments_url }}
